
after_everything do
  
  say_wizard "Git recipe running 'after everything'"
    append_file '.gitignore','/.idea'

  # Initialize new Git repo
  git :init
  git :add => '.'
  git :commit => "-aqm 'new Rails app generated by Rails Apps Composer gem'"
end

__END__

name: aai10_git
description: "Set up Git and commit the initial repository."
author: aai10

exclusive: scm
category: other
tags: [scm]
